language: python

# command to install dependencies
install:
    - "python setup.py install"

# command to run tests
script:
    - python -m pytest -v

stages:
    - name: test

jobs:
  fast_finish: true
  include:
    - stage: test
      python: "2.7"

    - stage: test
      python: "3.4"

    - stage: test
      python: "3.5"

    - stage: test
      python: "3.6"
